apiVersion: v2
name: infra-kafka
description: Infrastructure Kafka
icon: https://www.smarsh.com//media/smarsh-logo-new.svg
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: kafka
    repository: alias:kubernetes-charts
    version: 0.21.2
  - name: ml8scommon
    version: 1.2.0
    repository: alias:dr
